### ISSUE TITLE
No license text

### ISSUE THREAD

**Issue by schemetastic** [alexjedi/magnetic-wrapper#1]
I know that the README file has a statement that says that it is licensed under the MIT license, but there is no link or text for the license. This might could limit some people on the use of the project.

I'm not a lawyer... but ideally I believe it should have the text file, it can be more accessible.

**Comment by alexjedi** [comment]
Thank you @schemetastic, you are totally right! I have added the MIT file license to the project

**Comment by schemetastic** [comment]
Thanks! Can't wait to use it.
